# Generated by Django 4.2.7 on 2025-11-26 09:35

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('analyst', 'Data Analyst'), ('researcher', 'Researcher'), ('viewer', 'Viewer')], default='analyst', max_length=20)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('zip_code', models.CharField(max_length=10)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
                ('blood_pressure_systolic', models.IntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)])),
                ('blood_pressure_diastolic', models.IntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(150)])),
                ('treatment_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diagnosis', models.TextField()),
                ('admission_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'patients',
                'ordering': ['-admission_date'],
                'indexes': [models.Index(fields=['age'], name='patients_age_14e2c8_idx'), models.Index(fields=['gender'], name='patients_gender_99196d_idx'), models.Index(fields=['zip_code'], name='patients_zip_cod_d454fe_idx'), models.Index(fields=['admission_date'], name='patients_admissi_34fece_idx')],
            },
        ),
        migrations.CreateModel(
            name='EpsilonBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_budget', models.FloatField(default=10.0)),
                ('consumed_budget', models.FloatField(default=0.0)),
                ('warning_threshold', models.FloatField(default=2.0)),
                ('last_reset', models.DateTimeField(default=django.utils.timezone.now)),
                ('reset_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='epsilon_budget', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'epsilon_budgets',
            },
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_type', models.CharField(choices=[('count', 'Count'), ('mean', 'Mean'), ('sum', 'Sum'), ('median', 'Median'), ('histogram', 'Histogram')], max_length=20)),
                ('epsilon_used', models.FloatField()),
                ('delta_used', models.FloatField(default=0.0)),
                ('noise_scale', models.FloatField(blank=True, null=True)),
                ('query_params', models.JSONField(default=dict)),
                ('filters_applied', models.JSONField(default=dict)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('blocked', 'Blocked - Insufficient Budget'), ('error', 'Error')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('execution_time', models.FloatField(help_text='Execution time in seconds')),
                ('rows_affected', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'query_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='query_logs_user_id_407975_idx'), models.Index(fields=['query_type'], name='query_logs_query_t_6e46ba_idx'), models.Index(fields=['status'], name='query_logs_status_e80594_idx'), models.Index(fields=['-timestamp'], name='query_logs_timesta_8e2e40_idx')],
            },
        ),
    ]
